FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_BACKEND_URL
ARG VITE_GENERATE_URL
ARG VITE_GENERATE_USERNAME
ARG VITE_GENERATE_PASSWORD

ENV VITE_BACKEND_URL=$VITE_BACKEND_URL
ENV VITE_GENERATE_URL=$VITE_GENERATE_URL
ENV VITE_GENERATE_USERNAME=$VITE_GENERATE_USERNAME
ENV VITE_GENERATE_PASSWORD=$VITE_GENERATE_PASSWORD

RUN npm run build

FROM node:20-alpine AS runner

WORKDIR /app
RUN npm install -g serve
COPY --from=builder /app/dist ./dist
ENV PORT=8080
EXPOSE 8080

CMD serve -s dist -l $PORT